config/routes.rb
Geomarket::Application.routes.draw do
  post '/marketplace' => 'pages#marketplace'
  resources :orders

  resources :cart_items

  resources :carts

  resources :votes

  resources :farms

  resources :products
  
devise_for :users, :controllers => { :registrations => "registrations", :sessions => "sessions" }

  devise_scope :user do
    get "/login", :to => "devise/sessions#new", :as => :new_user_session
    get "/logout", :to => "devise/sessions#destroy", :as => :destroy_user_session
    get "/profile", :to => "devise/registrations#edit", :as => :profile
  end

  resources :users

  get 'profile' => 'registrations#edit', :as => 'profile'

  get 'home' => 'pages#home', :as => 'home'
  get 'admin' => 'admins#index', :as => 'admin'
  get 'marketplace' => 'pages#marketplace', :as => 'marketplace'
  get 'route' => 'pages#route', :as => 'route'
  get 'villageboard' => 'pages#village_board', :as => 'villageboard'
  get 'farmer' => 'pages#farmer', :as => 'farmer'
  get 'my_farm' => 'pages#my_farm', :as => 'my_farm'

  root :to => 'pages#home'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_one :order
  has_many :cart_items, :dependent => :destroy

  def delete_product(farm_product_id)
    current_item = cart_items.where(:farm_product_id => farm_product_id).first
      unless current_item.nil?
        if current_item.quantity > 1
           current_item.quantity -= 1
              cart_items << current_item
        else
           current_item.destroy
        end
      end
  end

  def add_farm_product(farm_product)
    current_item = cart_items.where(:farm_product_id => farm_product.id).first
    Rails.logger.debug(current_item.inspect)
    if current_item
      current_item.quantity += 1
    else
      current_item = cart_items.build(:farm_product_id => farm_product.id)
    end
    current_item
  end

  def total_price
    cart_items.to_a.sum { |item| item.total_price }
  end


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # GET /carts
  # GET /carts.xml
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.xml
  def show
    begin
      unless current_user.nil?
        @cart = Cart.find(params[:id])
        raise CartsHelper::NotMyCart unless @cart.user_id.eql?(current_user.id)
      else
        @cart = Cart.find session[:cart_id]
      end
      rescue ActiveRecord::RecordNotFound
        redirect_to marketplace_url, :notice => 'Invalid cart'
    else
      Rails.logger.debug('Cart show' + @cart.cart_items.inspect)
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @cart }
      end
      end
    rescue CartsHelper::NotMyCart => e
      redirect_to marketplace_url, :notice => e.message
    end
  end

  # GET /carts/new
  # GET /carts/new.xml
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.xml
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to(@cart, :notice => 'Cart was successfully created.') }
        format.xml  { render :xml => @cart, :status => :created, :location => @cart }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cart.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.xml
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to(@cart, :notice => 'Cart was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cart.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.xml
  def destroy
    @cart = current_user.cart.last
    @cart.cart_items.destroy_all
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to(root_url, :notice => 'Your cart is empty') }
      format.xml  { head :ok }
    end
  end

app/helpers/carts_helper.rb
module CartsHelper
  class NotMyCart < StandardError
    def message
      "This is not your cart!"
    end
  end
end

app/views/carts/_form.html.haml
= form_for @cart do |f|
  -if @cart.errors.any?
    #error_explanation
      %h2= "#{pluralize(@cart.errors.count, "error")} prohibited this cart from being saved:"
      %ul
        - @cart.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/carts/edit.html.haml
%h1 Editing cart

= render 'form'

= link_to 'Show', @cart
\|
= link_to 'Back', carts_path

app/views/carts/index.html.haml
%h1 Listing carts

%table
  %tr
    %th
    %th
    %th

  - @carts.each do |cart|
    %tr
      %td= link_to 'Show', cart
      %td= link_to 'Edit', edit_cart_path(cart)
      %td= link_to 'Destroy', cart, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Cart', new_cart_path

app/views/carts/new.html.haml
%h1 New cart

= render 'form'

= link_to 'Back', carts_path

app/views/carts/show.html.haml
- if @cart.cart_items.empty?
  #cart_title
    Your VillageStand Cart is Empty!
    = link_to 'Order something, please!', marketplace_url
- else

  %table
    %tr
      %th Product Name
      %th Farm
      %th Price
      %th Quantity
      %th Total Price
      %th Remove
      %th Add
      - @cart.cart_items.each do |item|
        %tr.cart_item_line
          %td
            = item.farm_product.product.title
          %td
            = item.farm_product.farm.name
          %td.price
            == #{item.farm_product.price}$
          %td.cart_item_quantity
            = item.quantity
          %td.total_price
            == #{item.total_price}$
          %td
            = link_to (image_tag 'remove.png'), cart_item_path(:farm_product_id => item.farm_product.id),
           :method =>:delete, :remote => true, :class => 'quantity-remove-link'
          %td
            = link_to (image_tag 'add.png'), cart_items_path(:farm_product_id => item.farm_product),
           :remote => true, :method => :post, :class => 'quantity-add-link'
  #total
    Total price:
    %span#money_total
      == #{@cart.total_price}$
  = link_to (image_tag 'remove_cart.png'), @cart, :method => :delete, :confirm => 'Are you really want to delete all cart items?'
  = link_to (image_tag 'checkout.png'), new_order_path