config/routes.rb
Geomarket::Application.routes.draw do
  post '/marketplace' => 'pages#marketplace'
  resources :orders

  resources :cart_items

  resources :carts

  resources :votes

  resources :farms

  resources :products
  
devise_for :users, :controllers => { :registrations => "registrations", :sessions => "sessions" }

  devise_scope :user do
    get "/login", :to => "devise/sessions#new", :as => :new_user_session
    get "/logout", :to => "devise/sessions#destroy", :as => :destroy_user_session
    get "/profile", :to => "devise/registrations#edit", :as => :profile
  end

  resources :users

  get 'profile' => 'registrations#edit', :as => 'profile'

  get 'home' => 'pages#home', :as => 'home'
  get 'admin' => 'admins#index', :as => 'admin'
  get 'marketplace' => 'pages#marketplace', :as => 'marketplace'
  get 'route' => 'pages#route', :as => 'route'
  get 'villageboard' => 'pages#village_board', :as => 'villageboard'
  get 'farmer' => 'pages#farmer', :as => 'farmer'
  get 'my_farm' => 'pages#my_farm', :as => 'my_farm'

  root :to => 'pages#home'

end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :farm_product

  def total_price
    farm_product.price * quantity
  end

end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  # GET /cart_items
  # GET /cart_items.xml
  def index
    @cart_items = CartItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @cart_items }
    end
  end

  # GET /cart_items/1
  # GET /cart_items/1.xml
  def show
    @cart_item = CartItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @cart_item }
    end
  end

  # GET /cart_items/new
  # GET /cart_items/new.xml
  def new
    @cart_item = CartItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cart_item }
    end
  end

  # GET /cart_items/1/edit
  def edit
    @cart_item = CartItem.find(params[:id])
  end

  # POST /cart_items
  # POST /cart_items.xml
  def create
    if current_user.nil?
    if session[:cart_id].nil?
        @cart = Cart.create
        @cart.save
        session[:cart_id] = @cart.id
    end
      @cart = Cart.find session[:cart_id]
    else
      @cart = current_user.carts.last
    end
    farm_product = FarmProduct.find(params[:farm_product_id])
      Rails.logger.debug(@cart.inspect)
    @cart_item = @cart.add_farm_product(farm_product)
      Rails.logger.debug(@cart_item.inspect)
    respond_to do |format|
      if @cart_item.save
        format.js { render :layout => false}
        format.html { redirect_to(:back) }
        format.xml  { render :xml => @cart_item, :status => :created, :location => @cart_item }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cart_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /cart_items/1
  # PUT /cart_items/1.xml
  def update
    @cart_item = CartItem.find(params[:id])

    respond_to do |format|
      if @cart_item.update_attributes(params[:cart_item])
        format.html { redirect_to(@cart_item, :notice => 'Cart item was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cart_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /cart_items/1
  # DELETE /cart_items/1.xml
  def destroy
    if current_user.nil?
      @cart = Cart.find session[:cart_id]
    else
      @cart = current_user.carts.last
    end
    farm_product = FarmProduct.find(params[:farm_product_id])
    @cart.delete_product(farm_product.id)
        respond_to do |format|
#          format.js { render :layout => false}
          format.html { redirect_to :back }
          format.xml  { head :ok }
        end


  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/_form.html.haml
= form_for @cart_item do |f|
  -if @cart_item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@cart_item.errors.count, "error")} prohibited this cart_item from being saved:"
      %ul
        - @cart_item.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :farm_product_id
    = f.text_field :farm_product_id
  .field
    = f.label :cart_id
    = f.text_field :cart_id
  .actions
    = f.submit 'Save'

app/views/cart_items/create.js.erb
<% unless session[:cart_id].nil? %>
    $('#cart-image a').attr('href', "<%= cart_path(Cart.find session[:cart_id]) %>");
<% end %>

app/views/cart_items/edit.html.haml
%h1 Editing cart_item

= render 'form'

= link_to 'Show', @cart_item
\|
= link_to 'Back', cart_items_path

app/views/cart_items/index.html.haml
%h1 Listing cart_items

%table
  %tr
    %th Farm product
    %th Cart
    %th
    %th
    %th

  - @cart_items.each do |cart_item|
    %tr
      %td= cart_item.farm_product_id
      %td= cart_item.cart_id
      %td= link_to 'Show', cart_item
      %td= link_to 'Edit', edit_cart_item_path(cart_item)
      %td= link_to 'Destroy', cart_item, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Cart item', new_cart_item_path

app/views/cart_items/new.html.haml
%h1 New cart_item

= render 'form'

= link_to 'Back', cart_items_path

app/views/cart_items/show.html.haml
%p#notice= notice

%p
  %b Farm product:
  = @cart_item.farm_product_id
%p
  %b Cart:
  = @cart_item.cart_id

= link_to 'Edit', edit_cart_item_path(@cart_item)
\|
= link_to 'Back', cart_items_path