config/routes.rb
Geomarket::Application.routes.draw do
  post '/marketplace' => 'pages#marketplace'
  resources :orders

  resources :cart_items

  resources :carts

  resources :votes

  resources :farms

  resources :products
  
devise_for :users, :controllers => { :registrations => "registrations", :sessions => "sessions" }

  devise_scope :user do
    get "/login", :to => "devise/sessions#new", :as => :new_user_session
    get "/logout", :to => "devise/sessions#destroy", :as => :destroy_user_session
    get "/profile", :to => "devise/registrations#edit", :as => :profile
  end

  resources :users

  get 'profile' => 'registrations#edit', :as => 'profile'

  get 'home' => 'pages#home', :as => 'home'
  get 'admin' => 'admins#index', :as => 'admin'
  get 'marketplace' => 'pages#marketplace', :as => 'marketplace'
  get 'route' => 'pages#route', :as => 'route'
  get 'villageboard' => 'pages#village_board', :as => 'villageboard'
  get 'farmer' => 'pages#farmer', :as => 'farmer'
  get 'my_farm' => 'pages#my_farm', :as => 'my_farm'

  root :to => 'pages#home'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_one :order
  has_many :cart_items, :dependent => :destroy

  def delete_product(farm_product_id)
    current_item = cart_items.where(:farm_product_id => farm_product_id).first
      unless current_item.nil?
        if current_item.quantity > 1
           current_item.quantity -= 1
              cart_items << current_item
        else
           current_item.destroy
        end
      end
  end

  def add_farm_product(farm_product)
    current_item = cart_items.where(:farm_product_id => farm_product.id).first
    Rails.logger.debug(current_item.inspect)
    if current_item
      current_item.quantity += 1
    else
      current_item = cart_items.build(:farm_product_id => farm_product.id)
    end
    current_item
  end

  def total_price
    cart_items.to_a.sum { |item| item.total_price }
  end


end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :farm_product

  def total_price
    farm_product.price * quantity
  end

end

app/models/farm.rb
class Farm < ActiveRecord::Base
  validates_presence_of :name, :harvest, :about, :offers, :logo, :address

  has_many :farm_products, :dependent => :destroy
  has_many :products, :through => :farm_products, :foreign_key => :product_id
  has_many :votes
  has_one :user

  accepts_nested_attributes_for :farm_products, :allow_destroy => true, :reject_if => :all_blank

  geocoded_by :address   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates
#  paginates_per 3
  attr_accessor :logo

  mount_uploader :logo, FarmsLogoUploader


end

app/models/farm_product.rb
class FarmProduct < ActiveRecord::Base
  belongs_to :farm
  belongs_to :product
  has_many :cart_items

  before_destroy :ensure_not_referenced_by_any_cart_item

  def ensure_not_referenced_by_any_cart_item
    if cart_items.count.zero?
      true
    else
      errors.add(:base, 'Items present in the cart')
      false
    end
  end
end

app/models/last_activity.rb
class LastActivity < ActiveRecord::Base
  def self.last
    all(:limit => 9,:order => 'created_At DESC')
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :cart
  validates_presence_of :ship_address, :city, :state, :zip, :cc_number, :telephone
  after_create :create_last_activity_message
  validate :credit_card_number

  def create_last_activity_message
    cart_id = self.cart_id
    unless Cart.find(cart_id).user.nil?
    LastActivity.create(:message => "#{Cart.find(cart_id).user.username} is ordered some vegetables.")
    else
    LastActivity.create(:message => "Someone is ordered some vegetables.")
    end
  end

  def credit_card_number
    errors.add_to_base("#{cc_number} is invalid credit card number") if cc_number.present? && !cc_number.creditcard?
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates_presence_of :title, :logo
  has_many :farm_products, :dependent => :destroy
  has_many :farms, :through => :farm_products, :foreign_key => :farm_id

  attr_accessor :logo

  mount_uploader :logo, ProductLogoUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :first_name, :last_name, :username
  validates_uniqueness_of :username

  has_many :carts
  has_many :votes
  has_one :farm

  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode  # auto-fetch address

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :role,
                  :latitude, :longitude,:first_name, :last_name, :username

  after_create :create_last_activity_message
  def create_cart(cart, order)
    Rails.logger.debug('cart is: ' + cart.inspect + 'order is: ' + order.inspect)
    if cart.nil? or cart.nil?
      unless Cart.last.try(:cart_items).empty?
        Cart.create(:user_id => self.id)
      end
    else
      cart = Cart.find(cart)
      cart.user_id = self.id
      cart.save
      Cart.create(:user_id => self.id)
    end
  end

  def create_last_activity_message
    LastActivity.create(:message => "#{self.username} is joined our community!")
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :farm, :counter_cache => true
  belongs_to :user
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  class NotMyCart < StandardError
    def message
      "This is not your cart!"
    end
  end
end

app/helpers/farms_helper.rb
module FarmsHelper

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper

  def products_left_to_show(counter)
    if ((counter - 4) <= 0 )
      'More'
    else
      "#{counter - 4}" + ' More'
    end
  end

  class NotMyFarm < StandardError
    def message
      "This is not your farm!"
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title Geomarket
    = stylesheet_link_tag 'print', :media => 'print'
    = stylesheet_link_tag 'screen', 'home', 'admin', :media => 'screen, projection'
    /[if IE]
      = stylesheet_link_tag 'ie'
    = javascript_include_tag 'jquery', 'nested_form', 'rails', 'application'
    = csrf_meta_tag
  %body
    .container#header
      #logo-image
        = link_to (image_tag 'logo.jpg'), root_url
      #cart-image
        -unless current_user.nil?
          = link_to (image_tag cart_has_items?, :id => 'cart-image-link'), cart_path(current_user.try(:carts).last)
      #auth-bar
        - if user_signed_in?
          == Signed in as #{link_to "#{current_user.username}", profile_url}. Not you? #{link_to "Sign out", destroy_user_session_path}
        %br You are in the admin section. Go to the #{link_to 'home page', root_url}

    .container
      = link_to 'Manage products', products_path, :id => 'products-admin'
      = link_to 'Manage farms', farms_path, :id => 'farms-admin'
      = link_to 'Manage orders', orders_path, :id => 'orders-admin'
      = link_to 'Manage users', users_path, :id => 'users-admin'
      - if flash[:notice]
        #notice
          = flash[:notice]
      = yield
    .container
      #footer
        #gift
          = image_tag 'gift.png', :id => 'giftimg'
          %br Give a VillageStand gift
        #bulkorder
          = image_tag 'order.png', :id => 'bulkimg'
          %br Business Login
        #footer-right
          #followus
            = image_tag 'twitter.png'
            = image_tag 'facebook.png'
            %br Follow us on
          #contact
            = image_tag 'contact.png', :id => 'contactimg'
            %br Contact us

app/views/layouts/application.haml
!!!
%html
  %head
    %title Geomarket
    %script{:src => "http://maps.google.com/maps/api/js?sensor=true", :type => "text/javascript"}
    = stylesheet_link_tag 'print', :media => 'print'
    = stylesheet_link_tag 'screen', 'home', 'jquery-ui-1.8.12.custom', :media => 'screen, projection'
    /[if IE]
      = stylesheet_link_tag 'ie'
    = javascript_include_tag 'jquery', 'BookmarkApp', 'nested_form', 'jquery-ui', 'rails', 'application'
    = hidden_field_tag :geolat
    = hidden_field_tag :geolong
    = csrf_meta_tag
  %body
    .container#header
      = render :partial => 'shared/header'
    .container#navigation
      = link_to 'Home', root_path, :id => 'home'
      = link_to 'Marketplace', marketplace_url, :id => 'marketplace'
      = link_to 'Village Board', nil, :id => 'village-board'
    .container
      - if flash[:notice]
        #notice
          = flash[:notice]
      = yield
    .container
      #footer
        #gift
          = image_tag 'gift.png', :id => 'giftimg'
          %br Give a VillageStand gift
        - if farmer?
          #bulkorder
            = link_to (image_tag 'order.png', :id => 'bulkimg'), farmer_url
            %br Business Login
        #footer-right
          #followus
            = image_tag 'twitter.png'
            = image_tag 'facebook.png'
            %br Follow us on
          #contact
            = image_tag 'contact.png', :id => 'contactimg'
            %br Contact us

app/views/pages/_google_map.html.haml
%script
  distance = []
  - @farms.each do |f|
    distance.push(['#{f.latitude}' + ',' + '#{f.longitude}' + ',' + '#{f.name}', #{f.distance_from(@address)}])
  distance.sort(sortMultiDimensional)
  user_coords = #{Geocoder.coordinates(@address)}
= javascript_include_tag 'homemap'

app/views/pages/farmer.html.haml
- if current_user.farm.nil?
  #farmer
    You don't have any associated with you farm.
    = link_to 'Create one?', new_farm_path
- else
  #farmer
    You have farm associated with you.
    = link_to 'Want to manage it?', my_farm_url(:id => current_user.farm.id)

app/views/pages/home.html.haml
.container#awarness
  1,234,432 pounds of freshness served
.container#information
  #text.span-12
    .large
      What is VillageStand?
    Not two farms are the same. Farm ho has best tomatos, Farm mo has best baby corn. Farm yo has best lettuce and
    Farm jo has best berries.Farm ho has best tomatos, Farm mo has best baby corn. Farm yo has best lettuce and
    Farm jo has best berries.Farm ho has best tomatos, Farm mo has best baby corn. Farm yo has best lettuce and
    Farm jo has best berries.
    Not two farms are the same. Farm ho has best tomatos, Farm mo has best baby corn. Farm yo has best lettuce and
    Farm jo has best berries.Farm ho has best tomatos, Farm mo has best baby corn. Farm yo has best lettuce and
    Farm jo has best berries.Farm ho has best tomatos, Farm mo has best baby corn. Farm yo has best lettuce and
    Farm jo has best berries.
  #video.span-12
    %object{:height => "349", :width => "425"}
      %embed{:allowfullscreen => "true", :allowscriptaccess => "always", :height => "349", :src => "http://www.youtube-nocookie.com/v/0xcGaaiDjX4?fs=1&hl=ru_RU&rel=0", :type => "application/x-shockwave-flash", :width => "425"}
.container#join-now
  #mobile-icons
    #android
      %span#android-image
        = image_tag 'android.png'
      %br Android
    #iphone
      %span#iphone-image
        = image_tag 'iphone.png'
      %br IPhone
    #blackberry
      %span#blackberry-image
        = image_tag 'blackberry.png'
      %br Blackberry
    #palm
      %span#palm-image
        =image_tag 'palm.png'
      %br Palm
  = button_to 'Join now!', new_user_registration_path, :method => :get, :id => 'joinbutton'
.container
  #live-feed
    - @last_activities.each do |message|
      .feed-message
        %b
          = time_ago_in_words message.created_at
        ago
        = message.message
  #map_canvas
    = render :partial => 'google_map'

app/views/pages/marketplace.html.haml
#sort
  %b Sort by
  = link_to 'Distance', marketplace_url(:sort_by => 'distance'), :id => 'distance-sort'
  = link_to 'Price', marketplace_url(:sort_by => 'price'), :id => 'price-sort'
#title-bar
#farms
  - @farms[0..3].each do |farm|
    .farm
      .farm-info
        %p
          = image_tag farm.logo.url.to_s
          = link_to farm.name, :action => 'village_board', :controller => 'pages', :farm => farm
          = link_to image_tag('route.jpg'), :action => 'route', :controller => 'pages', :id => farm
        %p
          Harvest:
          = farm.harvest
          days
        %p
          Distance:
          - if cookies[:latitude].nil? || cookies[:longitude].nil?
            = '%.2f' % farm.distance_from(@address)
          - else
            = '%.2f' % farm.distance_from([Float(cookies[:latitude]),Float(cookies[:longitude])])
          miles
        %p
          Votes:
          = farm.votes_count
        %p
          Offers:
          = farm.offers
      .farm-products
        - farm.farm_products[0..3].each do |fp|
          - product = Product.find(fp.product_id)
          %table.product-table
            %tr
              %td.image-td
                = image_tag product.logo.url.to_s
              %td.title-td
                = product.title
              %td.price-td
                == .#{fp.price} C/lbs
              %td.quantity-td
                == #{fp.quantity} lbs
              %td.cart-td
                = link_to (image_tag 'shopping_cart_add (1).png', :alt => product.title), cart_items_path(:farm_product_id => fp),
                :remote => true, :method => :post, :class => 'add_to_cart_link'
        %span#link-more
          = link_to products_left_to_show(farm.farm_products.count), :action => 'village_board', :controller => 'pages', :farm => farm
= will_paginate @farms

app/views/pages/my_farm.html.haml
%h1 Editing farm

= render 'farms/form'

= link_to 'Show', @farm
\|
= link_to 'All farms', farms_path

app/views/pages/route.html.haml
:javascript
  lat = '#{@address[0]}'
  long = '#{@address[1]}'
  flat = '#{@farm.latitude}'
  flong = '#{@farm.longitude}'
  destination = '#{@farm.address}'
= javascript_include_tag 'route'
#map_canvas

:css
  #map_canvas { height: 400px; width:950px;}

app/views/pages/village_board.html.haml
#farm-panel
  - unless current_user.nil?
    = form_for @vote, :remote => true do |f|

      = f.hidden_field "farm_id", :value => @farm.id
      = f.hidden_field "user_id", :value => current_user.id
      = link_to (image_tag 'favorite2.png'), 'javascript:void(0)', :onclick => 'return ATBookmarkApp.addBookmark(this)'
      = image_submit_tag "star.jpg"
#title-bar
#farm
  %ul
    %li
      %a{:href => "#farm-main"} Produce List
    %li
      %a{:href => "#farm-whats-around"} Whats happening
    %li
      %a{:href => "#farm-about"} About us
  #farm-about
    = @farm.about
  #farm-whats-around
    What's happening around? dunno yet...
  #farm-main
    #farm-info
      %p
        = image_tag @farm.logo.url.to_s
        = @farm.name
        = link_to image_tag('route.jpg'), :action => 'route', :controller => 'pages', :id => @farm
      %p
        Distance
        = '%.2f' % @farm.distance_from(@address)
        miles
      %p
        Harvest:
        = @farm.harvest
        days
      %p#highlight
        Votes:
        %span#votes-count
          = @farm.votes_count
      %p
        Offers:
        = @farm.offers
    #farm-products
      - @farm.farm_products.each do |fp|
        - product = Product.find(fp.product_id)
        %table.product-table
          %tr
            %td.image-td
              = image_tag product.logo.url.to_s
            %td.title-td
              = product.title
            %td.price-td
              = '.'+ fp.price.to_s + ' C/lbs'
            %td.quantity-td
              = fp.quantity
            %td.cart-td
              = link_to (image_tag 'shopping_cart_add (1).png', :alt => product.title), cart_items_path(:farm_product_id => fp),
              :remote => true, :method => :post, :class => 'add_to_cart_link'
:css
  #farm-panel {
  text-align: right;
  }

app/views/shared/_header.html.haml
#logo-image
  = link_to (image_tag 'logo.jpg'), root_url
#cart-image
  - unless current_user.nil?
    = link_to (image_tag cart_has_items?, :id => 'cart-image-link'), cart_path(current_user.try(:carts).last)
  - else
    - unless session[:cart_id].nil?
      = link_to (image_tag cart_has_items?, :id => 'cart-image-link'), cart_path(session[:cart_id])
    -else
      = link_to (image_tag 'shopping_cart.png', :id => 'cart-image-link'), '#'
#auth-bar
  - if user_signed_in?
    == Signed in as #{link_to "#{current_user.username}", profile_url}. Not you? #{link_to "Sign out", destroy_user_session_path}
    %p
      -if admin?
        You logged in as admin. Please visit
        = link_to 'admin section', admin_url
  - else
    #log-in
      = link_to "Sign up / Login with facebook", new_user_registration_path
    #sign-up
      = link_to "Sign in", new_user_session_path